# Generated by Django 2.0.2 on 2018-11-28 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back2back', '0003_finals_8'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='seeding',
        ),
    ]
