# Generated by Django 3.2.9 on 2022-12-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back2back', '0008_add_verified_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='category',
            field=models.CharField(choices=[('rm', 'Recurve Men'), ('rw', 'Recurve Women'), ('cm', 'Compound Men'), ('cw', 'Compound Women')], max_length=255),
        ),
    ]
